---
title: "De novo mutations of ASD"
author: "Shengtong  Han"
date: YYYY-MM-DD
output: html_document
---

<!-- The file analysis/chunks.R contains chunks that define default settings
shared across the workflowr files. -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

## Samples and reference windows


### Reference window

Example_windows_with_div_score.bed: each row is a 50bp window with a few features, such as mutation rate, coding, promoter, GC content, and divergence score. 


### Case Samples 



index    | Samples | \# mutations| \# subjects
----|-------|-------|---
1 | Jiang_cases_DNM.bed | 2,091| 32
2 | Michaelson_cases_DNM.bed |581 | 10
3 | Yuen_NM2015_cases_DNM.bed | 9,381| 162
4 | Wu_cases_DNM.bed | 1,915 | 32
5 | Kong_cases_DNM.bed | 4,930 | 78

Table: Five WGS  DNM case sample information



### Control sample 

index    | Samples | \# mutations| \# subjects
----|-------|-------|---
1 | Wong_NC_2016_693_control_SNV.bed | 27,092| 
Table:WGS  DNM control sample information 


<!-- Add your analysis here -->

## Session information


<!-- Insert the session information into the document -->
```{r session-info}
```
