---
title: "Genomic features"
author: "Shengtong Han"
date: YYYY-MM-DD
output: html_document
---

<!-- The file analysis/chunks.R contains chunks that define default settings
shared across the workflowr files. -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```


```{r load packages, results='hide', include=FALSE}
library(RSQLite)
library(dplyr)
library(knitr)
library(git2r)
```

<!-- Add your analysis here -->



## Genomic features 

These features are from the [reference data][data]

[data]:https://github.com/carjed/smaug-genetics


 11 binary features 

*  EXON:
* H3K4me1
* H3K4me3
* H3K9ac
* H3K9me3
* H3K27ac
* H3K27me3
* H3K36me3
* [CpGI][cpgi]

[cpgi]:http://web.stanford.edu/class/bios221/data/model-based-cpg-islands-hg19.txt

* LAMIN
* DHS (DNase  hypersensitive sites)

3 continuous features:

* RR (recombination rate)
* TIME (Replication timing)
* GC


## Session information

<!-- Insert the session information into the document -->
```{r session-info}
```
